#!/bin/bash

cd "$(dirname "$0")"

ret=0

function check() {
    if [ -e "$2/.bug" ]; then
	if [ $1 -ne 0 ]; then
            echo -ne "\e[35;1mBUG \e[0m"
	else
            echo -ne "\e[36;1mBUG_PASS\e[0m"
	fi
    else
	if [ $1 -ne 0 ]; then
	    local ignore="WITHMOCK_TEST_IGNORE_${2}"
	    if [ -n "${!ignore}" ]; then
		echo -ne "\e[30;1mIGNORE\e[0m"
	    else
		echo -ne "\e[31;1mFAIL\e[0m"
		ret=1
	    fi
	else
            echo -ne "\e[32;1mPASS\e[0m"
	fi
    fi
}

echo -n > test.log

echo -e "\e[33;1mscenarios\e[0m"
echo -e "========="
echo -e "                    withmock\tmocktest"
for d in $(ls -vd *); do
    if [ ! -d "${d}" ]; then
        continue
    fi
    printf "%-20s" "${d}:"
    echo "=== ${d} ===" >> test.log
    if [ -x "${d}/test.withmock" ]; then
        echo "--- withmock ---" >> test.log
        (cd $d; ./test.withmock) >> test.log 2>&1
	check $? $d
	echo -ne "\t"
    else
        echo -ne "\e[33;1mSKIP\e[0m\t"
    fi
    if [ -x "${d}/test.mocktest" ]; then
        echo "--- mocktest ---" >> test.log
        (cd $d; ./test.mocktest) >> test.log 2>&1
	check $? $d
	echo ""
    else
        echo -e "\e[33;1mSKIP\e[0m"
    fi
done

exit $ret
