#!/bin/bash

ret=0

echo -e "\e[33;1mgo install\e[0m"
echo -e "=========="
echo -n "withmock: "
echo "=== withmock ===" > test.log
go install github.com/qur/withmock >> test.log 2>&1
if [ $? -ne 0 ]; then
    echo -e "\e[31;1mFAIL\e[0m"
    ret=1
else
    echo -e "\e[32;1mPASS\e[0m"
fi
echo -n "mocktest: "
echo "=== mocktest ===" >> test.log
go install github.com/qur/withmock/mocktest >> test.log 2>&1
if [ $? -ne 0 ]; then
    echo -e "\e[31;1mFAIL\e[0m"
    ret=1
else
    echo -e "\e[32;1mPASS\e[0m"
fi
echo -n "mkgomock: "
echo "=== mkgomock ===" >> test.log
go install github.com/qur/withmock/mkgomock >> test.log 2>&1
if [ $? -ne 0 ]; then
    echo -e "\e[31;1mFAIL\e[0m"
    ret=1
else
    echo -e "\e[32;1mPASS\e[0m"
fi

exit $ret
