#!/bin/bash

mydir="$(dirname "$0")"
mydir="$(cd "${mydir}"; pwd)"

logfile="${mydir}/vtest.log"

gopath="${mydir}/tst"
code="${gopath}/src/code"

mkdir -p "${code}"

version="$1"
shift;

cd "${mydir}"

exec 3>&1 >"${logfile}" 2>&1

goroot="${version}/go"

export GOROOT="${mydir}/${goroot}"
export GOPATH="${gopath}"
export PATH="$GOROOT/bin:$PATH"

echo "==== ${version} ===="
(cd "${code}"; "${mydir}/runtest" mocktest "$@")
ret=$?
echo

pc=$(grep pass "${logfile}" | wc -l)
fc=$(grep fail "${logfile}" | wc -l)

echo "pass: ${pc}, fail: ${fc}" >&3

exit $ret
